### ISSUE TITLE
pip install fails: No such file or directory: 'pypi.rst'

### ISSUE THREAD

**Issue by mturley** [blairbonnett/pylabels#2]
I can't seem to use pip to install pylabels.  I've tried this on both Ubuntu and Mac OS, and both give me the below output.  Cloning the project from github and running `python setup.py install` seems to work normally, however.

```
$ sudo pip install pylabels
Downloading/unpacking pylabels
  Downloading pylabels-1.1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pylabels/setup.py) egg_info for package pylabels
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pylabels/setup.py", line 5, in <module>
        with open('pypi.rst') as f:
    IOError: [Errno 2] No such file or directory: 'pypi.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pylabels/setup.py", line 5, in <module>

    with open('pypi.rst') as f:

IOError: [Errno 2] No such file or directory: 'pypi.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pylabels
Storing debug log for failure in /home/mturley/.pip/pip.log
```

**Comment by blairbonnett** [comment]
Sorry about that. I've uploaded version 1.1.2 which includes the missing file in the distribution and installs OK on my computer.

**Comment by mturley** [comment]
No worries, thanks for the quick response!  By the way, I'm loving pylabels.  I've been using it to build a replacement for an old crusty PHP/imagemagick label generator for my mom's small business.  So much easier to work with and maintain.

**Comment by blairbonnett** [comment]
Thanks, always nice to know its coming in handy.
